### ISSUE TITLE
Incorrect NFT sale prices in nft.trades

### ISSUE THREAD

**Issue by catherine-2** [duneanalytics/spellbook#1510]
I've noticed there are a lot of incorrect NFT sale prices in the Dune v2 nft.trades table. Seems like a pretty large sized issue -- for Moonbirds Opensea trades over the last 2 months 46% of sales are affected and show the incorrect price. 

Not sure what is causing this as it affects both WETH accepts + ETH buy now listings.

Two examples:
select * 
from nft.trades
where tx_hash in (
    lower('0xf3e876be22e90a8f339c140411e1aa73ca63999ee2c8cd3b0d22054447695b46') -- 11.8 WETH sale showing as 12.685 in amount_original
    , lower ('0x0846007a3049edc73ae36ef069dfba9a11a02ebe8381c34963b715ff66499910') -- 14.99 ETH buy now sale showing as 16.11425 in amount_original
    )

Opensea links:
https://opensea.io/assets/ethereum/0x23581767a106ae21c074b2276d25e5c3e136a68b/5344
https://opensea.io/assets/ethereum/0x23581767a106ae21c074b2276d25e5c3e136a68b/9099

**Comment by catherine-2** [comment]
I figured out how this bug is happening.

Example on 11.8 ETH sale that is showing as 12.685
https://etherscan.io/tx/0xf3e876be22e90a8f339c140411e1aa73ca63999ee2c8cd3b0d22054447695b46

The numbers should be:
Sale price = 11.8
OS fee = 0.295
Royalty = 0.59
Amount to seller = 10.915

Second example on 14.99 that is showing as 16.11425
https://etherscan.io/tx/0x0846007a3049edc73ae36ef069dfba9a11a02ebe8381c34963b715ff66499910

Sale price = 14.99
OS fee = 0.37475
Royalty = 0.7495
Amount to seller = 13.86575


Somehow the amount_original column in the nft.trades table v2 for OpenSea is showing the sale price + OS fee + royalty instead of just the sales price. (e.g. 11.8+0.295+0.59 = 12.685 that is showing up in the data table right now instead of the correct 11.8)

I'm not familiar with the underlying code -- can take a look -- but wanted to flag in the meantime in case someone else is more familiar and knows how this is happening!

**Comment by catherine-2** [comment]
@soispoke saw you were listed as the nft.trades contributor on the docs so wanted to flag for you as well! I searched the underlying code and couldn't tell at first read through how this is happening.

**Comment by soispoke** [comment]
Thanks, I think it would be nice if @sohwak from the OpenSea team could take a look at this ?

**Comment by catherine-2** [comment]
@sohwak any thoughts on what is causing this error?

**Comment by catherine-2** [comment]
@soispoke  @sohwak  sorry for the double ping! Wanted to check back in and see if you have any thoughts on this? 

I still can't figure out what is causing this error in the code from going through the different underlying tables even though I figured out the math that is causing it. Wondering if maybe it is due to some field issues (e.g. pulling in wrong one someplace)? I've noticed some of the most recent trades are correct so not sure if it could be an old bug and we need to refresh old data? 

The scale of this issue is pretty big so I'm having to convert v2 tables back to v1 and creating all new tables on v1 again.

**Comment by sohwak** [comment]
@catherine-2 sorry for late reply. I will take look at it.

**Comment by catherine-2** [comment]
@sohwak  thank you!

**Comment by 0xRobin** [comment]
⚠️ this seems like a pretty big issue.
@sohwak @soispoke @jeff-dude 
 Based on manual sample checks, I believe we are miscounting **A LOT** of transactions:
 
###  Issue coverage
 | Call function  | checks | examples | 
| ------------- | ------------- | ---------- |
| `fulfillAdvancedOrder` | 🔴 | [ex1](https://etherscan.io/tx/0xf3e876be22e90a8f339c140411e1aa73ca63999ee2c8cd3b0d22054447695b46), [ex2](https://etherscan.io/tx/0x0846007a3049edc73ae36ef069dfba9a11a02ebe8381c34963b715ff66499910) |
| `fulfillAvailableAdvancedOrders`  | 🟢 ||
| `fulfillAvailableOrders` | 🟢 ||
| `fulfillBasicOrder` | 🟢 ||
| `fullfillOrder` | 🔴| [ex1](https://etherscan.io/tx/0x83ac7a6bdfe944e87ab4fff7463401bfc7fc2cf724c5e0c1a966e29ecfd63d35), [ex2](https://etherscan.io/tx/0x580f4d4b350884b24c36ae0719e3d23a8943bd4fdee5e07e4b509ec9928a9ce4) |
| `matchAdvancedOrders` | 🟡 | other issue found (underreporting price): [ex](https://etherscan.io/tx/0xb7dcca50ffef23121f0f326aac946c886c958b7e6eee2747393015053e8f269a) |
| `matchOrders` | 🟢 | |

### Impact estimations
https://dune.com/queries/1280576
958,829 bugged trades (out of 5,996,245) **[~16%]**
$198,942,070 bugged volume (out of $1,519,733,609) **[~13%]**
results in an estimated **$13,190,225 excess volume reported**

### Issue
The issue seems to result in double counting the `royalty_fee` and `platform_fee` amounts in the `original_amount`.
It seems only contained to the `p3` calculations in the query

The query code however is a bit of a mess (spent probably ~6h going through it and still unsure what's causing the issue, reverse engineering the structure is not really feasible if you're not familiar)

### Quickfix
simple fix, a more thorough refactor of this query seems advised though. 
https://github.com/duneanalytics/spellbook/pull/1572

**Comment by catherine-2** [comment]
@0xRobin Thank you so much for digging into this!! I was really struggling to find the cause in the query code

**Comment by soispoke** [comment]
Hey @0xRobin, thanks a lot for the work you put in + pushing a quick fix for this issue. I agree this spell should be cleaned up.
Just to make sure I understand, your #1572 fix changes resolve `fulfillAdvancedOrder` and `fullfillOrder` you reported, but not matchAdvancedOrders ?

**Comment by 0xRobin** [comment]
@soispoke correct.
The `matchAdvancedOrders` issue is unrelated and has a lower impact.
I've described it here in Issue https://github.com/duneanalytics/spellbook/issues/1573

**Comment by 0xRobin** [comment]
Also I want to be clear, the PR fixes the symptoms we are observing (double counting fees).
But I still have no clue where the origin of the problem lies.  🤷

**Comment by soispoke** [comment]
@0xRobin Got it thanks, will merge your PR until maybe @sohwak can dive deeper into this

**Comment by sohwak** [comment]
I might find where the major difference occurred. 
some volumes are over-calculated. When we say volume, usually it means the total paid amount and includes both platform fees and royalties. but in some parts, it was double-calculated.

**Comment by sohwak** [comment]
yep. @0xRobin already found and make PR this. I am going to look at this PR

**Comment by sohwak** [comment]
> Yes it's unclear to me if `offer[0].amount` and/or `consideration[0].amount` should be fee inclusive or fee exclusive.. Looks like that's not always consistent?

it is different up to buy or offer-accepted. when buying items, amount would be paid once and then distributed, but when accepting offers, amount would be paid directly and seperately.
