### ISSUE TITLE
[BUG] perpetual.trades has a varchar/varbinary error in DuneSQL

### ISSUE THREAD

**Issue by MSilb7** [duneanalytics/spellbook#3019]
### Description

The perpetual.trades spell works properly in Spark, but is unusable in DuneSQL. It returns an error `Failed analyzing stored view 'delta_prod.perpetual.trades': line 27:5: column 16 in UNION query has incompatible types: varchar, double at line 1, position 15.`

See: https://dune.com/queries/2254707

### Current behavior

Table is unusable in DuneSQL

### Expected behavior

Table is usable in DuneSQL, like it is in SparkSQL

### Impacted model(s)

```
perpetual.trades
```

### Possible solution

Can we have help debugging where this error is? There are many contributing spells, so hard to know where the issue is.

cc @RplusT

**Comment by 0xRobin** [comment]
We can further debug this:
`column 16` indicates that the `volume_raw` column is to blame.

We can then use
```
SHOW COLUMNS FROM perpetual_protocol.perpetual_trades LIKE 'volume_raw'
```

to inspect the schema for each of the sub models. 

perpetual_protocol -> **varchar**
pika -> double
synthetix -> **varchar**
emdx_avalanche_c -> double
hubble_exchange_avalanche_c -> double
gmx -> double

Both these models where added yesterday in https://github.com/duneanalytics/spellbook/pull/2839 so that seems to add up.
@RplusT Are you able to open a PR that correctly casts this column?

cc @belen-pruvost for visibility on dunesql issues.

**Comment by belen-pruvost** [comment]
+ @jmsgu for visibility on dunesql issues

**Comment by MSilb7** [comment]
Ah, the error did say double. My brain automatically saw varbinary haha.
