### ISSUE TITLE
[BUG] oneinch_unoswap_v5_ethereum_trades spell contains outlier tx's which explode the amount values

### ISSUE THREAD

**Issue by jeff-dude** [duneanalytics/spellbook#3030]
### Description

a handful of transactions coming from the source `oneinch_ethereum.AggregationRouterV5_call_unoswap` in the `oneinch_unoswap_v5_ethereum_trades` spell incorrectly join to the `ethereum.traces` base table. the single join condition in question is [here](https://github.com/duneanalytics/spellbook/blob/main/models/oneinch/ethereum/unoswap/oneinch_unoswap_v5_ethereum_trades.sql#L120). the tx's in question:
[0x4f98ac5d5778203a0df3848c85494a179eae35befa64bb6fc360f03851385191](https://etherscan.io/tx/0x4f98ac5d5778203a0df3848c85494a179eae35befa64bb6fc360f03851385191)
[0xce87a97efbf1c6c0491a72997d5239029ced77c9ef7413db66cc30b4da63fe86](https://etherscan.io/tx/0xce87a97efbf1c6c0491a72997d5239029ced77c9ef7413db66cc30b4da63fe86)
[0x62c833c1ab66d17c42aeb1407755c00894f9af8691da2c2ca0f14392e3a6334c](https://etherscan.io/tx/0x62c833c1ab66d17c42aeb1407755c00894f9af8691da2c2ca0f14392e3a6334c)
[0x774ad4c15a6f776e71641fe4e9af3abd5bb80f7511c77548d130c2ee124ba80a](https://etherscan.io/tx/0x774ad4c15a6f776e71641fe4e9af3abd5bb80f7511c77548d130c2ee124ba80a)

**_please note:_** this is also an issue on v1 engine, so it's not an issue with migration to v2 engine, but rather the logic itself. the "quick fix" on v1 engine was to just force the `usd_amount` to `0` to remove outlier values that blow up dashboard visuals.
### Current behavior

all transactions from `oneinch_ethereum.AggregationRouterV5_call_unoswap` outside of the linked above work fine within the context of the current code join conditions. in the initial build of this spell, some of the tx's were manually filtered out as they seemed to be outliers. then new ones appeared every so often and are not filtered out, therefore showing high `amount_usd` for a few transactions.

[here is a query](https://dune.com/queries/2181607?sidebar=none) which is a subset of the spell to narrow down the complexity and focus on the three tx's joined to traces, **_with the troubled join condition commented out_** so we can see visually the two options each tx has to choose from. the row for each tx where array size column output is the same is which would be chosen in the join condition.

when the incorrect join happens, it provides an incorrect token amount associated, which then leads to exploding value in `amount_usd` downstream.

screenshot of current behavior, which has token sold the same in both rows of the transaction:
<img width="1407" alt="image" src="https://user-images.githubusercontent.com/102681548/227381386-17bae9e1-d967-480c-84fc-6bca4e292e40.png">

### Expected behavior

the screenshot above should have a different token sold for each row. since the join to traces from above is pulling the wrong row, it leads to this output. then the calculations on amounts get out of sync.

### Impacted model(s)

```
oneinch_unoswap_v5_ethereum_trades
```
three tx's linked above
### Possible solution

is it possible to rewrite that one line of the join condition to include a `CASE` statement on the source unoswap trace address to add `2` or `3` depending on certain situations? i'm not sure what those situations are, but it seems like something needs further clarified.

**Comment by jeff-dude** [comment]
@andrewhong5297 apologies for the random tag, but i'm wondering if you have any idea how to help debug this issue? or potentially can help tag someone who can?

**Comment by andrewhong5297** [comment]
> @andrewhong5297 apologies for the random tag, but i'm wondering if you have any idea how to help debug this issue? or potentially can help tag someone who can?

I'll look into this!

**Comment by sjmillius** [comment]
https://etherscan.io/tx-decoder?tx=0xad7d5814544440bdcb22760f8f2f0594958e9e6417249d96d92bf78cd05a80f5
is another example, where this leads to dune incorrectly interpreting the value as USDC (instead of ETH), blowing amount_usd up (~1 ETH is interpreted as ~1 trillion USDC)

**Comment by jeff-dude** [comment]
in the short term, we'll need to write a test to look for these tx's as they pop up and fix accordingly

**Comment by sjmillius** [comment]
Without having looked now too deeply into this:
is this only popping up/visibles if tokens like USDC etc. are involved that have a much lower representation digits than e.g. ETH. Could it be that it's often wrong, but less visible, because mixing up the tokens involved don't create such obvious outliers?

**Comment by jeff-dude** [comment]
yeah, decimals is part of it. it will incorrectly divide token raw amount (which this field is correct) by the wrong decimal, then also multiply by wrong price on top of that. code here:
https://github.com/duneanalytics/spellbook/blob/main/models/oneinch/ethereum/unoswap/oneinch_unoswap_v5_ethereum_trades.sql#L177-L192

**Comment by sjmillius** [comment]
The join condition here seems wrong:
https://github.com/duneanalytics/spellbook/blob/970088f3422ee6ebf8b3189c7bf3f9a00cabb5ea/models/oneinch/ethereum/unoswap/oneinch_unoswap_v5_ethereum_trades.sql#LL123C5-L123C5

```sql
AND COALESCE(array_size(unoswap.call_trace_address), 0) + 2 = COALESCE(array_size(traces.trace_address), 0)
```

In the example here:

![trace](https://github.com/duneanalytics/spellbook/assets/31015782/337dbeff-d7fa-47fc-b9d9-98bbea539d82)

Where we have a STG -> USDC -> WETH swap, 
the second swap has a different nesting and the trace address is [2, 4, 0, 0].

![trace_address](https://github.com/duneanalytics/spellbook/assets/31015782/014d4c0b-155e-4672-985c-7a7499a21384)

The + 2 in the join above assumes a specific structure that is not given in the SwapsPair contract (https://etherscan.io/token/0x6e1fbeeaba87bae1100d95f8340dc27ad7c8427b).

Shouldn't the last transfer (originating from the unoswap call) be enough.
Why was 
```sql
AND COALESCE(array_size(unoswap.call_trace_address), 0) + 2 = COALESCE(array_size(traces.trace_address), 0)
```
added, that should not be needed? 
With that condition the second and final transfer call is lost.

**Comment by jeff-dude** [comment]
thank you for digging in and providing an example 🙏 

i don't have much of a reason for the join other than "that's how it was built on v1 engine, then migrated spellbook as-is". i'm certainly open to looking into removing the condition altogether or altering. the only condition is that we need to prove this modification doesn't impact all other tx's in the contract.

if you feel comfortable doing it, please do open a PR with the change and then the attached gh action for CI test will build a test table with full historical data. you can then use that test table on the dune app itself for ~24 hours to query and view results. we should then be able to compare the test table to the actual spell itself with some joins.

**Comment by sjmillius** [comment]
This is a bit more nuanced (or complicated).
I relaxed / removed the join condition and ran a test on trades from 2023-04-01 to today.
While this solves the hardcoded excluded exceptions that are currently in the spell and correctly classifies others, such as:
https://etherscan.io/tx-decoder?tx=0x815eb87513e5928bae0a213303c53649264d3fa6633cf2c1ca976515d1a44f55
here is a VERSE-WETH swap, currently the token-bought is null:
```sql
select *
  from dex_aggregator.trades
 where tx_hash = 0x815eb87513e5928bae0a213303c53649264d3fa6633cf2c1ca976515d1a44f55
```
![query-results](https://github.com/duneanalytics/spellbook/assets/31015782/6a3f32d0-39c1-4c5e-905c-ac3d5af4f820)

Another one from this category is [0xf9bcf9e2dddc50ce1f927797bb88bb7c0fbf415f195af96a9a7c013dc5e9d500](https://etherscan.io/tx-decoder?tx=0xf9bcf9e2dddc50ce1f927797bb88bb7c0fbf415f195af96a9a7c013dc5e9d500)

It seems swaps via Verse Exchange (such as the ones above) are problematic - as they are typically proxy contracts, they might break the join condition (as calls are more deeply nested). These are guess examples don't easily produce noticeable outliers. 

Unfortunately, relaxing the join condition also produces incorrect results sometimes:

Consider the following trade:
https://etherscan.io/tx-decoder?tx=0x17d97f39fd07fe0e4c4f609ef822beff9bdea04aac7f22ec80563abafad76e66

Here we have a swap from ROW -> WETH -> PP
(currently correctly classified in dex_aggregators.trades)

But you can see in the execution trace that the PP transfer was not the last transfer called: 
![RWO-WETH-PP](https://github.com/duneanalytics/spellbook/assets/31015782/92c06a15-4f72-441c-981d-416f47059000)

The last transfer is a PEPE transfer. This is because PP (https://printthepepe.com/) distributes PEPE to PP holders.
So the transfer of PP triggers a distribution and hence transfer of PEPE.

Another one like that (but for SHARBI, but here the existing logic doesn't get it either):
(0x63dfb02a31e5603dbc974537de552f70706a8704295bd15eb4b06407a6747063)[https://etherscan.io/tx-decoder?tx=0x63dfb02a31e5603dbc974537de552f70706a8704295bd15eb4b06407a6747063]

I'm not sure that this can solved correctly using that kind of join.

The correct thing would probably be to look at the last pool in the chain in the unoswap call, and get the token information from there?

**Comment by jeff-dude** [comment]
i'll be out until early next week, but plz feel free to keep digging here -- this is good stuff!

**Comment by jeff-dude** [comment]
fyi @grkhr -- leaving this issue open until we either rework the 1inch spells (feeding `dex_aggregator.trades`) or replace them completely

**Comment by grkhr** [comment]
@jeff-dude we are currently working on it! planning to completely rework the logic and make everything clean like in `oneinch_lop_macro`

**Comment by jeff-dude** [comment]
> @jeff-dude we are currently working on it! planning to completely rework the logic and make everything clean like in `oneinch_lop_macro`

fantastic! i'll close this then.
