### ISSUE TITLE
[BUG] 1inch Aggregator Trades

### ISSUE THREAD

**Issue by bh2smith** [duneanalytics/spellbook#3277]
Invalid Trade value on 1inch trade

[This Query](https://dune.com/queries/2437658?category=abstraction&namespace=dex_aggregator&table=trades&blockchains=arbitrum+avalanche_c+bnb+ethereum+fantom+gnosis+optimism) shows 2B $ for a trade that is clearly only about 1k

[Etherscan](https://etherscan.io/tx/0xafba4b3db26b0e9f26d0ca4c709e80ee2b8bc18e3298fa67126697fc45fba0c6)

looks like its coming from [this file](https://github.com/duneanalytics/spellbook/blob/main/models/oneinch/ethereum/oneinch_v5_ethereum_trades.sql) but its a bit too involved for me to properly investigate at the moment.

**Comment by jeff-dude** [comment]
this is a new tx which falls into #3030 bug that is yet to be solved. it happens when there are three tokens involved, two being a stablecoin such as usdc/usdt/etc, weth/eth & then a random token. in this case, that's verse.

it's actually [this script](https://github.com/duneanalytics/spellbook/blob/main/models/oneinch/ethereum/unoswap/oneinch_unoswap_v5_ethereum_trades.sql#L35) and this comment is intending to call it out. the join [here](https://github.com/duneanalytics/spellbook/blob/main/models/oneinch/ethereum/unoswap/oneinch_unoswap_v5_ethereum_trades.sql#L122) on trace address is causing the issue, but i'm not sure how to fix without breaking the correct 99%+ of tx's.

if your expertise on traces can help me out -- it'd be much appreciated!
