### ISSUE TITLE
[BUG] Incorrect 1inch Trade Value

### ISSUE THREAD

**Issue by bh2smith** [duneanalytics/spellbook#3400]
There is something wrong with the `token_sold_amount` in this Offending Order from 1inch trades (cc @jeff-dude). It does not appear to be a decimal places issue, but the number is just WAY OFF!

[Transaction](https://etherscan.io/tx/0x14613a8f439f5f65b3235fbae95b67bc5f6aa7b0937af73e8df593e00d8abb12) shows 51876554662 USDC atoms being sold.

[Dune](https://dune.com/queries/2503595?category=abstraction&namespace=dex_aggregator&table=trades&blockchains=arbitrum+avalanche_c+bnb+ethereum+fantom+gnosis+optimism) shows 8433663266628000000000

**Comment by augustog** [comment]
gm @bh2smith thanks for flagging!

I narrowed it to [this](https://github.com/duneanalytics/spellbook/blob/5ce386603e88725556cf37e8f5361f86a0ebffe3/models/oneinch/ethereum/uniswap/oneinch_uniswap_v3_ethereum_trades.sql#LL93C83-L93C83) source table.

The row in the decoded table shows the same amount we see here ([src](https://dune.com/queries/2504838)), so in principle this is not some weird behaviour on the spell level, maybe a wrong assumption on the logic? Do we know of a scenario where  `uniswapV3Swap` can be called with a value for `amount` different than the amount sold?

**Comment by bh2smith** [comment]
I can take a closer look tomorrow!

**Comment by jeff-dude** [comment]
documenting some findings, as i dig in a bit more. we're getting test failures, as `amount_usd` is blown out of proportion, due to the `amount_raw` being incorrect.
- as pointed out, the tx comes from [this decoded table](https://github.com/duneanalytics/spellbook/blob/5ce386603e88725556cf37e8f5361f86a0ebffe3/models/oneinch/ethereum/uniswap/oneinch_uniswap_v3_ethereum_trades.sql#L93)
- for token_sold, there is a CTE in the script which joins to `traces` base table, to pull to `to` and `from` columns. the `to` is used to help derive the `token_sold_address` -- which for this tx highlighted, points to USDC address
![image](https://github.com/duneanalytics/spellbook/assets/102681548/60a7db2a-457f-4add-9cb1-87a472e7d204)
- while the address for token_sold comes from `traces`, the `amount` comes from decoded table
![image](https://github.com/duneanalytics/spellbook/assets/102681548/dbbf7310-f0c4-4b9b-a94e-488cec300aed)

i can't see anything else other than this may be an issue with the raw data (or a decoded table bug). i will raise to the appropriate teammates to help us continue investigate.

for reference, [here is the query](https://dune.com/queries/2636216?d=1&sidebar=none) for quick views

**Comment by bh2smith** [comment]
Well that would make sense, since USDC has only 6 decimals and result in an 18 decimal token being blown out of proportion by a factor of `10^{18 - 6}` (whatever that is).

**Comment by jeff-dude** [comment]
1inch team has also looked, and for now the tx is manually excluded from the spell. this is an outlier tx.
