### ISSUE TITLE
[Request] Create `evms` tables at the ingestion level or materialise them

### ISSUE THREAD

**Issue by hildobby** [duneanalytics/spellbook#4693]
With blockchain data becoming increasingly segmented across chains, I created the `evms` sector a few months ago for crosschain analysis. It currently consists of a view with all chains in one for each raw table type. With it being a view, performance is pretty bad, and it's been been getting worse as more chains go live on Dune and are added to that table. Now my spells using it often timeout on the large engine when they wouldn't have a few weeks ago.

It does seem like quite a few queries use those tables, here is just for `evms.transactions`: https://dune.com/browse/queries?q=evms.transactions&order=created_at&codeSearch=1

Would it be possible to have those tables either created at the ingestion level or be materialised? 

cc @jeff-dude @aalan3

**Comment by aalan3** [comment]
The main problem here is that materializing this will probably unfortunately not give us the performance gain we want. Querying  evms.transactions for example is basically like querying the would-be materialized version partitioned by blockchain (which is probably how we would have materialized it as well).

The reason why this is not performing well is that there is a lot of data being joined or combined, having a bigger table means more data is going to have to be sorted which is why this is so slow and with each new chain it just because bigger.

And ideally for both UX and performance reasons, most queries shouldn't be hitting base tables that's why we have decoded tables and spells. 

So I think we should explore the following things:
- Cross chain decoded tables (something similar to `evms.erc20_transfers` actually) - I've been looking at this a bit but need to do more research internally as well
- More cross chain aggregations of transactions, traces or logs
- Potentially denormalizing decoded date more, meaning we add more columns to decoded data which in turn would be turned cross chain via the first point above

What do you think about this and do you have any suggestions for the above?

**Comment by MSilb7** [comment]
Re-raised "native evms" here: https://github.com/duneanalytics/spellbook/issues/5257

Similar use case: "For OP Chains dashboards, what is the ideal structure?"
`select ... from op_chains.transactions` vs `select ... from evms.transactions where blockchain in (select blockchain from ...)` vs `select ... from optimism.transactions union all select ... from base.transactions union all select ... from zora.transactions union all [remember to add each new chain`

**Comment by jeff-dude** [comment]
closing this to track solely in one issue #5257
